export default {
  CTP_GR4VY_ADDRESS_DETAIL_ID_ADDRESS : 'gr4vyShippingDetailId',
  CTP_GR4VY_BUYER_ID_FIELD: {
    NAME: "gr4vyBuyerId",
    TYPE: "type",
    CUSTOMER_KEY: "customer-gr4vyBuyerId",
    ORDER_KEY: "order-gr4vyBuyerId",
  },

  //Locales
  defaultLocale: "en",

  TYPE_TRANSACTION: 'transaction',
  STATUS_PROCESSING: 'processing',
  STATUS_PROCESSING_FAILED: 'processing_failed',
  STATUS_CAPTURE_SUCCEEDED: 'capture_succeeded',
  STATUS_CAPTURE_PENDING: 'capture_pending',
  STATUS_CAPTURE_DECLINED: 'capture_declined',
  STATUS_CAPTURE_FAILED: 'capture_failed',
  STATUS_AUTHORIZATION_SUCCEEDED: 'authorization_succeeded',
  STATUS_AUTHORIZATION_PENDING: 'authorization_pending',
  STATUS_AUTHORIZATION_DECLINED: 'authorization_declined',
  STATUS_AUTHORIZATION_FAILED: 'authorization_failed',
  STATUS_AUTHORIZATION_EXPIRED: 'authorization_expired',
  STATUS_AUTHORIZATION_VOIDED: 'authorization_voided',
  STATUS_AUTHORIZATION_VOID_PENDING: 'authorization_void_pending',
  STATUS_AUTHORIZATION_VOID_DECLINED: 'authorization_void_declined',
  STATUS_AUTHORIZATION_VOID_FAILED: 'authorization_void_failed',
  STATUS_REFUND_SUCCEEDED: 'refund_succeeded',
  STATUS_REFUND_PENDING: 'refund_pending',
  STATUS_REFUND_DECLINED: 'refund_declined',
  STATUS_REFUND_FAILED: 'refund_failed',
  STATUS_BUYER_APPROVAL_SUCCEEDED: 'buyer_approval_succeeded',
  STATUS_BUYER_APPROVAL_PENDING: 'buyer_approval_pending',
  STATUS_BUYER_APPROVAL_DECLINED: 'buyer_approval_declined',
  STATUS_BUYER_APPROVAL_FAILED: 'buyer_approval_failed',
  STATUS_BUYER_APPROVAL_TIMEDOUT: 'buyer_approval_timedout',
  REFUND_STATUS_PROCESSING: 'processing',
  REFUND_STATUS_SUCCEEDED: 'succeeded',
  REFUND_STATUS_DECLINED: 'declined',
  REFUND_STATUS_FAILED: 'failed',
  REFUND_STATUS_VOIDED: 'voided',
}
